### ISSUE TITLE
Fails swagger-tools validation

### ISSUE THREAD

**Issue by somboo** [bobby-brennan/fhir-swagger#4] opened 2016-10-05 17:59 UTC
The output of fhir-swagger fails swagger-tools validation with 1311 errors.  Is this project still actively maintained?  Is there any plan to update the code to produce swagger compliant output?  If so, what timeline is reasonable for an update?  Thanks.

**Comment by lomori** [comment] 2017-01-18 22:47
+1. It looks like it's not maintained anymore.

**Comment by rbren** [comment] 2017-01-18 22:50
@somboo sorry for the delay, I missed your message.

I haven't had time to keep this up-to-date, but will happily accept PRs. Getting it to pass validation is definitely a priority but unfortunately I can't provide a timeline.

**Comment by lomori** [comment] 2017-01-18 22:55
That's great, thanks. It's generating a quite large Swagger files and I'm a bit lost. Do you have a general idea of what is causing the incompatibilities?

**Comment by rbren** [comment] 2017-01-18 23:16
I don't, but you can use http://bigstickcarpet.com/swagger-parser/www/index.html to check.  Feel free to post the errors here and I can offer some guidance

**Comment by lomori** [comment] 2017-01-20 19:23
I've been using http://editor.swagger.io/#/. I believe that's from the guys that started Swagger.

There are quite a few errors. The ones I've identified so far:

1. "$schema": "http://json-schema.org/draft-04/schema#": this generates a weird error. Why is this necessary? It's pointing to a draft. The default schema seems to be http://swagger.io/v2/schema.json#. If you are OK with removing it, where is it coming from? I did a grep and found it on two swagger.json but those seem to be only outputs of some tests.

2. The superfluous piece below has to be removed:
             "items": {
                "required": [],
                "properties": {}
             }

3. "type": "reference" is not allowed. Maybe change to "type": "string".

4. "items" is required for arrays. All fhir_comments for example don't have it.

5. "required" : [] -> should be removed.

I will search for where are all those coming from.

**Comment by rbren** [comment] 2017-01-20 20:10
Thanks for all the details. The errors you mentioned are all from JSONSchema issues. The JSONSchema is generated here:

https://github.com/bobby-brennan/fhir-swagger/blob/master/lib/schemas.js

The issue is probably with the [json-schema-generator](https://github.com/krg7880/json-schema-generator) library, which uses example JSON objects to generate a schema.  I'd be fine with changing libraries (e.g. to https://github.com/Nijikokun/generate-schema) or making post-hoc changes to the generated schemas (like deleting the `$schema` field or empty `required` arrays)

**Comment by rbren** [comment] 2017-03-02 23:43
Validation errors should be fixed in 2.2.0

**Closed as completed by rbren** 2017-03-02 23:43 UTC
